const postContainer = document.getElementById("post-container");
const fetchMessageButton = document.getElementById("fetch-message-button");
const viewSavedButton = document.getElementById("view-saved-button");

function saveMessage(message) {
    let savedMessages = JSON.parse(localStorage.getItem("savedMessages")) || [];
    savedMessages.unshift({ text: message, date: new Date().toLocaleString() });
    localStorage.setItem("savedMessages", JSON.stringify(savedMessages));
}

function typeMessage(element, text, speed = 50) {
    element.innerHTML = "";
    let i = 0;
    function type() {
        if (i < text.length) {
            element.innerHTML += text.charAt(i);
            i++;
            setTimeout(type, speed);
        }
    }
    type();
}

async function displayMessage() {
    postContainer.innerHTML = "<p>Loading a new message for you... ❤️</p>";

    try {
        const response = await fetch("/.netlify/functions/getMessage");
        const data = await response.json();

        if (data.error) {
            postContainer.innerHTML = `<p>Error fetching message: ${data.error}</p>`;
            return;
        }

        let message = data.message;
        if (!message.includes("❤️") && !message.includes("🥰") && !message.includes("💖")) {
            message += " ❤️🥰💖";
        }

        saveMessage(message);

        const postElement = document.createElement("div");
        postElement.classList.add("post");

        const heading = document.createElement("h3");
        heading.innerText = `New Message (Generated by: ${data.model || "Unknown Model"})`;

        const messageContainer = document.createElement("p");
        messageContainer.style.whiteSpace = "pre-line";
        messageContainer.style.fontFamily = "'Noto Color Emoji', sans-serif";

        postElement.appendChild(heading);
        postElement.appendChild(messageContainer);
        postContainer.innerHTML = "";
        postContainer.appendChild(postElement);

        typeMessage(messageContainer, message);
    } catch (error) {
        postContainer.innerHTML = `<p>Could not create message. Please try again later.</p>`;
    }
}

function displaySavedMessages() {
    const savedMessages = JSON.parse(localStorage.getItem("savedMessages")) || [];
    let savedContent = "<h2>Saved Messages</h2>";
    
    if (savedMessages.length === 0) {
        savedContent += "<p>No saved messages yet!</p>";
    } else {
        savedMessages.forEach((entry, index) => {
            savedContent += `<div class="post"><h3>Message ${index + 1} (${entry.date})</h3><p>${entry.text}</p></div>`;
        });
    }

    document.getElementById("saved-content").innerHTML = savedContent;
    document.getElementById("saved-container").style.display = "block";
}

function closeSavedView() {
    document.getElementById("saved-container").style.display = "none";
}

function createFloatingHeart() {
    const heart = document.createElement("div");
    heart.innerHTML = "❤️";
    heart.classList.add("floating-heart");
    heart.style.left = `${Math.random() * 100}vw`;
    heart.style.animationDuration = `${3 + Math.random() * 2}s`;
    document.body.appendChild(heart);
    setTimeout(() => heart.remove(), 5000);
}

setInterval(createFloatingHeart, 1000);

fetchMessageButton.addEventListener("click", displayMessage);
viewSavedButton.addEventListener("click", displaySavedMessages);
document.getElementById("close-saved").addEventListener("click", closeSavedView);